name: CI Pipeline for Mule Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Définir les variables d'environnement et les secrets au niveau du job
    env:
      http_host: ${{ env.HTTP_HOST }}    # Variable d'environnement créée dans GitHub Actions
      http_port: ${{ env.HTTP_PORT }}    # Variable d'environnement créée dans GitHub Actions
      API_KEY: ${{ secrets.API_KEY }}    # Secret créé dans GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Étape pour afficher les variables d'environnement et les secrets (optionnel, pour vérifier)
      # ATTENTION : ne jamais afficher le secret en production
      - name: Display environment variables and secrets
        run: |
          echo "HTTP Host: $http_host"
          echo "HTTP Port: $http_port"
          echo "API Key: $API_KEY" # Attention, ne pas garder cette ligne en production !

      - name: Build Mule project
        run: |
          mvn clean install

      - name: Display success message
        if: success()
        run: echo "Build succeeded! The Mule project has been built successfully."
