on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Load environment variables from .env and .secret files
        run: |
          export $(grep -v '^#' .env | xargs)
          export $(grep -v '^#' .secret | xargs)

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # Étape pour afficher les variables d'environnement et les secrets
      - name: Display environment variables and secrets
        run: |
          echo "HTTP Host: $http_host"
          echo "HTTP Port: $http_port"
          echo "API Key: $API_KEY" # Attention, ne pas garder cette ligne en production !
        env: 
          http_host: ${{ env.http_host }}
          http_port: ${{ env.http_port }}
          API_KEY: ${{ secrets.API_KEY }}  # Secret récupéré de GitHub

      - name: Build Mule project
        run: |
          mvn clean install
        env: 
          http.host: ${{ env.http_host }}
          http.port: ${{ env.http_port }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Display success message
        if: success()
        run: echo "Build succeeded! The Mule project has been built successfully."
