name: CI Pipeline for Mule Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Définir les variables d'environnement au niveau du job
    env:
      HTTP_HOST: ${{ vars.HTTP_HOST }}    # Variable d'environnement créée dans GitHub Actions
      HTTP_PORT: ${{ vars.HTTP_PORT }}    # Variable d'environnement créée dans GitHub Actions
      API_KEY: ${{ secrets.API_KEY }}      # Secret créé dans GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Étape pour afficher les variables d'environnement et les secrets (optionnel)
      - name: Display environment variables and secrets
        run: |
          echo "HTTP Host: $HTTP_HOST"
          echo "HTTP Port: $HTTP_PORT"
          echo "API Key: $API_KEY" # Attention, ne pas garder cette ligne en production !

      - name: Build Mule project
        run: |
          mvn clean install

      - name: Display success message
        if: success()
        run: echo "Build succeeded! The Mule project has been built successfully."
